name: Review workflow
on:
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  build:
    name: Review job
    runs-on: [self-hosted, default, any]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build
